# Generated by Django 5.1.5 on 2025-02-15 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_room_practice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingcycle',
            options={'ordering': ['-start_date'], 'verbose_name': 'Abrechnungszyklus', 'verbose_name_plural': 'Abrechnungszyklen'},
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Rechnungsnummer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='notes',
            field=models.TextField(blank=True, help_text='Interne Notizen zur Abrechnung', null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Datum des Zahlungseingangs', null=True),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('in_progress', 'In Bearbeitung'), ('submitted', 'Eingereicht'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Datum der Ausstellung durch den Arzt', verbose_name='Ausstellungsdatum'),
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_amount', models.DecimalField(decimal_places=2, help_text='Betrag der von der Krankenkasse zu zahlen ist', max_digits=10)),
                ('patient_copay', models.DecimalField(decimal_places=2, help_text='Zuzahlungsbetrag des Patienten', max_digits=10)),
                ('is_billed', models.BooleanField(default=False, help_text='Wurde bereits abgerechnet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_items', to='core.appointment')),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_items', to='core.billingcycle')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_items', to='core.prescription')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_items', to='core.treatment')),
            ],
            options={
                'verbose_name': 'Abrechnungsposition',
                'verbose_name_plural': 'Abrechnungspositionen',
            },
        ),
        migrations.CreateModel(
            name='PatientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Erstellt'), ('sent', 'Gesendet'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
