# Generated by Django 5.1.5 on 2025-02-15 17:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_billingcycle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surcharge',
            options={'verbose_name': 'Preiskonfiguration', 'verbose_name_plural': 'Preiskonfigurationen'},
        ),
        migrations.AddField(
            model_name='surcharge',
            name='valid_from',
            field=models.DateField(default=datetime.date.today, help_text='Gültig ab diesem Datum'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Gültig bis zu diesem Datum (leer = unbegrenzt gültig)', null=True),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='insurance_payment',
            field=models.DecimalField(decimal_places=2, help_text='Betrag, den die Krankenkasse zahlt', max_digits=10),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='insurance_provider_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.insuranceprovidergroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='patient_payment',
            field=models.DecimalField(decimal_places=2, help_text='Zuzahlungsbetrag des Patienten', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='surcharge',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='surcharge_valid_date_range'),
        ),
    ]
