# Generated by Django 5.1.5 on 2025-02-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_surcharge_options_surcharge_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingcycle',
            options={'verbose_name': 'Abrechnungszyklus', 'verbose_name_plural': 'Abrechnungszyklen'},
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='billingcycle',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='insurance_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insuranceprovider'),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('ready', 'Bereit zum Export'), ('exported', 'Exportiert'), ('completed', 'Abgeschlossen')], default='draft', max_length=20),
        ),
    ]
