# Generated by Django 5.1.5 on 2025-02-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_billingcycle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.practitioner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('confirmed', 'Bestätigt'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert'), ('no_show', 'Nicht erschienen')], default='planned', max_length=20),
        ),
    ]
