# Generated by Django 5.1.5 on 2025-02-15 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointment_practitioner_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surcharge',
            name='surcharge_valid_date_range',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='surcharge',
            name='valid_until',
            field=models.DateField(default=datetime.date(2099, 12, 31)),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='insurance_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='patient_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='valid_from',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
