# Generated by Django 5.1.5 on 2025-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_surcharge_surcharge_valid_date_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('confirmed', 'Bestätigt'), ('completed', 'Abgeschlossen'), ('ready_to_bill', 'Abrechnungsbereit'), ('billed', 'Abgerechnet'), ('cancelled', 'Storniert'), ('no_show', 'Nicht erschienen')], default='planned', max_length=20),
        ),
    ]
