# Generated by Django 5.1.5 on 2025-02-17 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_patient_email_alter_patient_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practitioner',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Therapeut', 'verbose_name_plural': 'Therapeuten'},
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='default_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
