# Generated by Django 5.1.5 on 2025-02-17 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_practitioner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Raum', 'verbose_name_plural': 'Räume'},
        ),
        migrations.RemoveField(
            model_name='practice',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='website',
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='practice',
        ),
        migrations.AddField(
            model_name='room',
            name='is_home_visit',
            field=models.BooleanField(default=False, help_text='Dieser Raum ist für Hausbesuche und nicht an Praxisöffnungszeiten gebunden', verbose_name='Hausbesuchsraum'),
        ),
        migrations.AddField(
            model_name='room',
            name='opening_hours',
            field=models.JSONField(default=dict, help_text='Öffnungszeiten des Raums (muss innerhalb der Praxisöffnungszeiten liegen)'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='bank_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='practice',
            name='bundesland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bundesland'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='practice',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='practice',
            name='institution_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='practice',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='practice',
            name='opening_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='practice',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='practice',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='practice',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='practice',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='practice',
            name='tax_id',
            field=models.CharField(max_length=20),
        ),
    ]
