# Generated by Django 5.1.5 on 2025-02-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_room_options_remove_practice_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='opening_hours',
            field=models.JSONField(default=dict),
        ),
    ]
