# Generated by Django 5.1.5 on 2025-02-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_room_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='opening_hours',
            field=models.JSONField(default=dict, help_text="Format: {'day': {'open': bool, 'hours': 'HH:MM-HH:MM'}}"),
        ),
    ]
