# Generated by Django 5.1.5 on 2025-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_room_opening_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Raum', 'verbose_name_plural': 'Räume'},
        ),
        migrations.AlterField(
            model_name='room',
            name='is_home_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='opening_hours',
            field=models.JSONField(default=dict),
        ),
    ]
