# Generated by Django 5.1.5 on 2025-02-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_room_options_alter_room_is_home_visit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practitioner',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Behandler', 'verbose_name_plural': 'Behandler'},
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='default_room',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='user',
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
