# Generated by Django 5.1.5 on 2025-02-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_practitioner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='position_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
