# Generated by Django 5.1.5 on 2025-05-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_treatment_position_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raetsel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gitterbreite', models.IntegerField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('gitter', models.JSONField()),
            ],
            options={
                'verbose_name': 'Rätsel',
                'verbose_name_plural': 'Rätsel',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='practice',
            name='calendar_settings',
            field=models.JSONField(default=dict, verbose_name='Kalendereinstellungen'),
        ),
        migrations.AddField(
            model_name='practice',
            name='default_appointment_duration',
            field=models.IntegerField(default=30, help_text='Standard-Terminlänge in Minuten', verbose_name='Standard-Terminlänge'),
        ),
        migrations.AddField(
            model_name='practice',
            name='invoice_settings',
            field=models.JSONField(default=dict, verbose_name='Rechnungseinstellungen'),
        ),
        migrations.AddField(
            model_name='practice',
            name='notification_settings',
            field=models.JSONField(default=dict, verbose_name='Benachrichtigungseinstellungen'),
        ),
        migrations.AddField(
            model_name='practice',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='bank_details',
            field=models.JSONField(default=dict, help_text='Bankverbindung der Praxis', verbose_name='Bankverbindung'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='bundesland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bundesland', verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='institution_code',
            field=models.CharField(max_length=20, verbose_name='Institutionskennzeichen'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Praxisname'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='opening_hours',
            field=models.JSONField(default=dict, help_text='Öffnungszeiten für jeden Wochentag', verbose_name='Öffnungszeiten'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Inhaber'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='street_address',
            field=models.CharField(max_length=255, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='tax_id',
            field=models.CharField(max_length=20, verbose_name='Steuernummer'),
        ),
    ]
