# Generated by Django 5.1.5 on 2025-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_raetsel_practice_calendar_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesland',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
