# Generated by Django 5.1.5 on 2025-05-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_bundesland_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='practice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.practice'),
        ),
    ]
