# Generated by Django 5.1.5 on 2025-06-12 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_room_practice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinghour',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('vacation', 'Urlaub'), ('sick', 'Krankheit'), ('parental_leave', 'Elternzeit'), ('special_leave', 'Sonderurlaub'), ('training', 'Fortbildung'), ('other', 'Sonstiges')], max_length=20, verbose_name='Abwesenheitsgrund'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='treatment_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_prescriptions', to='core.treatment'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Montag'), ('Tuesday', 'Dienstag'), ('Wednesday', 'Mittwoch'), ('Thursday', 'Donnerstag'), ('Friday', 'Freitag'), ('Saturday', 'Samstag'), ('Sunday', 'Sonntag')], max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='workinghour',
            unique_together={('practitioner', 'day_of_week', 'start_time', 'end_time', 'valid_from')},
        ),
    ]
