# Generated by Django 5.1.5 on 2025-06-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_workinghour_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalHoliday',
        ),
    ]
