# Generated by Django 5.1.5 on 2025-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_localholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_accent_color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Akzentfarbe'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_compact_mode',
            field=models.BooleanField(default=False, verbose_name='Kompakter Modus'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_font_size',
            field=models.CharField(choices=[('small', 'Klein'), ('medium', 'Mittel'), ('large', 'Groß')], default='medium', max_length=20, verbose_name='Schriftgröße'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Hell'), ('dark', 'Dunkel'), ('auto', 'Automatisch')], default='light', max_length=20, verbose_name='Theme-Modus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Der Benutzername darf maximal 150 Zeichen haben.'}, help_text='Benötigt. 150 Zeichen oder weniger. Buchstaben, Ziffern und @/./+/-/_ nur.', max_length=150, unique=True, verbose_name='Benutzername'),
        ),
    ]
