# Generated by Django 5.2.3 on 2025-07-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_set_admin_for_superusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='total_insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gesamtbetrag der Krankenkasse', max_digits=10),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='total_patient_copay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gesamtzuzahlung der Patienten', max_digits=10),
        ),
    ]
