# Generated by Django 5.1.5 on 2025-08-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_billing_cycle_totals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['treatment_name'], 'verbose_name': 'Behandlung', 'verbose_name_plural': 'Behandlungen'},
        ),
        migrations.AddField(
            model_name='treatment',
            name='self_pay_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preis für Selbstzahler-Behandlungen (ohne Verordnung)', max_digits=10, null=True, verbose_name='Selbstzahler-Preis'),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_items', to='core.prescription'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='is_self_pay',
            field=models.BooleanField(default=False, verbose_name='Selbstzahler-Behandlung'),
        ),
        migrations.AlterUniqueTogether(
            name='billingitem',
            unique_together={('appointment', 'billing_cycle')},
        ),
    ]
