# Generated by Django 5.1.5 on 2025-08-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_treatment_options_treatment_self_pay_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('completed', 'Abgeschlossen'), ('ready_to_bill', 'Abrechnungsbereit'), ('billed', 'Abgerechnet'), ('cancelled', 'Storniert'), ('no_show', 'Nicht erschienen')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField(verbose_name='Verfügbar ab')),
                ('available_until', models.DateTimeField(verbose_name='Verfügbar bis')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('urgent', 'Dringend')], default='medium', max_length=10, verbose_name='Priorität')),
                ('status', models.CharField(choices=[('waiting', 'Wartend'), ('offered', 'Angeboten'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt'), ('expired', 'Abgelaufen')], default='waiting', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.appointment', verbose_name='Ursprünglicher Termin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.patient', verbose_name='Patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practitioner', verbose_name='Behandler')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prescription', verbose_name='Verordnung')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.treatment', verbose_name='Behandlung')),
            ],
            options={
                'verbose_name': 'Warteliste',
                'verbose_name_plural': 'Wartelisten',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_at', models.DateTimeField(auto_now_add=True, verbose_name='Angeboten am')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Angenommen am')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgelehnt am')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appointment', verbose_name='Angebotener Termin')),
                ('waitlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offers', to='core.waitlist', verbose_name='Warteliste')),
            ],
            options={
                'verbose_name': 'Wartelisten-Angebot',
                'verbose_name_plural': 'Wartelisten-Angebote',
                'unique_together': {('waitlist', 'appointment')},
            },
        ),
        migrations.AddField(
            model_name='waitlist',
            name='offered_appointments',
            field=models.ManyToManyField(related_name='waitlist_offers', through='core.WaitlistOffer', to='core.appointment', verbose_name='Angebotene Termine'),
        ),
    ]
