# Generated by Django 5.1.5 on 2025-08-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_waitlist_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gebühr bei kurzfristiger Absage oder No-Show', max_digits=10, null=True, verbose_name='Absage-Gebühr'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_fee_charged',
            field=models.BooleanField(default=False, verbose_name='Gebühr berechnet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Gebühr bezahlt'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Absage-Notizen'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('no_show', 'Nicht erschienen'), ('late_cancellation', 'Kurzfristige Absage (< 24h)'), ('very_late_cancellation', 'Sehr kurzfristige Absage (< 2h)'), ('emergency', 'Notfall'), ('illness', 'Krankheit'), ('other', 'Sonstiges')], max_length=50, null=True, verbose_name='Absage-Grund'),
        ),
        migrations.AddField(
            model_name='practice',
            name='cancellation_fee_settings',
            field=models.JSONField(default=dict, help_text='Einstellungen für No-Show und Absage-Gebühren', verbose_name='Absage-Gebühren Einstellungen'),
        ),
    ]
