# Generated by Django 5.2.3 on 2025-08-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_appointment_cancellation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='accounting_code',
            field=models.CharField(blank=True, help_text='3-stelliger Abrechnungscode für die spezifische Leistung', max_length=3, null=True, verbose_name='Abrechnungscode (AC)'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_telemedicine',
            field=models.BooleanField(default=False, help_text='Gibt an, ob es sich um eine telemedizinische Leistung handelt', verbose_name='Telemedizinische Leistung'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='legs_code',
            field=models.CharField(blank=True, help_text='Leistungserbringergruppenschlüssel (AC.TK) für GKV-Abrechnung', max_length=10, null=True, verbose_name='LEGS-Code'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='prescription_type_indicator',
            field=models.CharField(blank=True, help_text="z.B. 'VKZ 10' für nachträglich abgegebene Leistungen", max_length=10, null=True, verbose_name='Verordnungsartkennzeichnung'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='tariff_indicator',
            field=models.CharField(blank=True, help_text='2-stelliges Tarifkennzeichen für die Vergütungshöhe', max_length=2, null=True, verbose_name='Tarifkennzeichen (TK)'),
        ),
    ]
