# Generated by Django 5.1.5 on 2025-08-08 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_legs_codes_to_treatments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_insurance',
            field=models.ForeignKey(blank=True, help_text='Versicherung des Patienten zum Zeitpunkt des Termins', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patientinsurance', verbose_name='Patientenversicherung'),
        ),
    ]
