# Generated by Django 5.2.3 on 2025-08-08 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_appointment_patient_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='insurance_claim_created',
            field=models.BooleanField(default=False, help_text='Krankenkassen-Anspruch erstellt'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='is_gkv_billing',
            field=models.BooleanField(default=False, help_text='GKV-Abrechnung: Zuzahlung wird Patient berechnet, Rest über Krankenkasse'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='is_private_billing',
            field=models.BooleanField(default=False, help_text='Private Abrechnung: Gesamtbetrag wird Patient berechnet'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='is_self_pay_billing',
            field=models.BooleanField(default=False, help_text='Selbstzahler: Gesamtbetrag wird Patient berechnet'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='is_telemedicine',
            field=models.BooleanField(default=False, help_text='Telemedizinische Leistung'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='legs_code',
            field=models.CharField(blank=True, help_text='LEGS-Code für GKV-Abrechnung', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='patient_invoice_created',
            field=models.BooleanField(default=False, help_text='Patientenrechnung für Zuzahlung erstellt'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='prescription_type_indicator',
            field=models.CharField(blank=True, help_text='Verordnungsartkennzeichnung (VKZ)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='GKVInsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(help_text='Eindeutige Anspruchsnummer', max_length=50, unique=True)),
                ('claim_date', models.DateField(auto_now_add=True, help_text='Datum der Anspruchserstellung')),
                ('total_insurance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Gesamtbetrag der Krankenkasse', max_digits=10)),
                ('total_patient_copay', models.DecimalField(decimal_places=2, default=0, help_text='Gesamtzuzahlung der Patienten', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('ready', 'Bereit zum Export'), ('exported', 'Exportiert'), ('paid', 'Bezahlt'), ('rejected', 'Abgelehnt')], default='draft', max_length=20)),
                ('export_date', models.DateTimeField(blank=True, null=True)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='gkv_exports/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gkv_claims', to='core.billingcycle')),
                ('insurance_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gkv_claims', to='core.insuranceprovider')),
            ],
            options={
                'verbose_name': 'GKV-Krankenkassen-Anspruch',
                'verbose_name_plural': 'GKV-Krankenkassen-Ansprüche',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientCopayInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Eindeutige Rechnungsnummer', max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True, help_text='Rechnungsdatum')),
                ('due_date', models.DateField(help_text='Fälligkeitsdatum')),
                ('total_copay', models.DecimalField(decimal_places=2, help_text='Gesamtzuzahlungsbetrag', max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Erstellt'), ('sent', 'Gesendet'), ('paid', 'Bezahlt'), ('overdue', 'Überfällig'), ('cancelled', 'Storniert')], default='created', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Bar'), ('bank_transfer', 'Überweisung'), ('card', 'Karte'), ('other', 'Sonstiges')], max_length=20, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='patient_invoices/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gkv_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_invoices', to='core.gkvinsuranceclaim')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copay_invoices', to='core.patient')),
            ],
            options={
                'verbose_name': 'Patienten-Zuzahlungsrechnung',
                'verbose_name_plural': 'Patienten-Zuzahlungsrechnungen',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='PrivatePatientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Eindeutige Rechnungsnummer', max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True, help_text='Rechnungsdatum')),
                ('due_date', models.DateField(help_text='Fälligkeitsdatum')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Gesamtbetrag der Rechnung', max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Erstellt'), ('sent', 'Gesendet'), ('paid', 'Bezahlt'), ('overdue', 'Überfällig'), ('cancelled', 'Storniert')], default='created', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Bar'), ('bank_transfer', 'Überweisung'), ('card', 'Karte'), ('other', 'Sonstiges')], max_length=20, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='private_invoices/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_invoices', to='core.billingcycle')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_invoices', to='core.patient')),
            ],
            options={
                'verbose_name': 'Private Patientenrechnung',
                'verbose_name_plural': 'Private Patientenrechnungen',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
