# Generated by Django 5.2.3 on 2025-08-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_billingitem_insurance_claim_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=255, verbose_name='Feiertagsname')),
                ('date', models.DateField(verbose_name='Datum')),
                ('is_recurring', models.BooleanField(default=True, help_text='Jährlich wiederkehrender Feiertag', verbose_name='Jährlich wiederkehrend')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundesland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bundesland', verbose_name='Bundesland')),
            ],
            options={
                'verbose_name': 'Feiertag',
                'verbose_name_plural': 'Feiertage',
                'ordering': ['date'],
                'unique_together': {('bundesland', 'date')},
            },
        ),
    ]
