# Generated by Django 5.2.3 on 2025-08-08 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_local_holiday_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Zahlungsdatum')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Zahlungsbetrag', max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Bar'), ('bank_transfer', 'Überweisung'), ('card', 'Karte'), ('direct_debit', 'Lastschrift'), ('check', 'Scheck'), ('other', 'Sonstiges')], help_text='Zahlungsart', max_length=20)),
                ('payment_type', models.CharField(choices=[('gkv_copay', 'GKV-Zuzahlung'), ('private_invoice', 'Private Rechnung'), ('self_pay', 'Selbstzahler'), ('insurance_claim', 'Krankenkassen-Anspruch'), ('other', 'Sonstiges')], help_text='Zahlungstyp', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Referenznummer (z.B. Überweisungsreferenz)', max_length=100)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaktions-ID', max_length=100)),
                ('is_confirmed', models.BooleanField(default=True, help_text='Zahlung bestätigt')),
                ('notes', models.TextField(blank=True, help_text='Zusätzliche Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copay_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.patientcopayinvoice')),
                ('created_by', models.ForeignKey(blank=True, help_text='Benutzer der die Zahlung erstellt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.patientinvoice')),
                ('private_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.privatepatientinvoice')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
