# Generated by Django 5.2.3 on 2025-08-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Zugeordneter Betrag', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Verknüpfte Termin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_fully_allocated',
            field=models.BooleanField(default=False, help_text='Zahlung vollständig zugeordnet'),
        ),
        migrations.AddField(
            model_name='payment',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Verknüpfte Verordnung', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.prescription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Verbleibender Betrag', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('gkv_copay', 'GKV-Zuzahlung'), ('private_invoice', 'Private Rechnung'), ('self_pay', 'Selbstzahler'), ('insurance_claim', 'Krankenkassen-Anspruch'), ('prescription_payment', 'Verordnungszahlung'), ('appointment_payment', 'Termin-Zahlung'), ('other', 'Sonstiges')], help_text='Zahlungstyp', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Zugeordneter Betrag', max_digits=10)),
                ('allocation_date', models.DateField(auto_now_add=True, help_text='Zuordnungsdatum')),
                ('notes', models.TextField(blank=True, help_text='Notizen zur Zuordnung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.appointment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.payment')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='core.prescription')),
            ],
            options={
                'verbose_name': 'Zahlungszuordnung',
                'verbose_name_plural': 'Zahlungszuordnungen',
                'ordering': ['-allocation_date'],
            },
        ),
    ]
