# Generated by Django 5.2.3 on 2025-08-15 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_payment_allocation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='follow_up_number',
            field=models.IntegerField(default=0, help_text='Nummer der Folgeverordnung (1, 2, 3, ...)', verbose_name='Folgeverordnungsnummer'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_follow_up',
            field=models.BooleanField(default=False, help_text='Gibt an, ob dies eine Folgeverordnung ist', verbose_name='Folgeverordnung'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='original_prescription',
            field=models.ForeignKey(blank=True, help_text='Verweis auf die ursprüngliche Verordnung bei Folgeverordnungen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_prescriptions', to='core.prescription', verbose_name='Ursprüngliche Verordnung'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Verordnung für diesen Termin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.prescription', verbose_name='Verordnung'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Open', 'Offen'), ('In_Progress', 'In Behandlung'), ('Completed', 'Abgeschlossen'), ('Cancelled', 'Storniert'), ('Extended', 'Verlängert')], default='Open', max_length=20),
        ),
    ]
