# Generated by Django 5.1.5 on 2025-08-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_follow_up_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesettings',
            name='auto_billing',
            field=models.BooleanField(default=False, verbose_name='Automatische Rechnungserstellung'),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='billing_cycle_days',
            field=models.IntegerField(default=30, verbose_name='Abrechnungszyklus (Tage)'),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='default_payment_terms',
            field=models.IntegerField(default=14, verbose_name='Standard-Zahlungsziel (Tage)'),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='E-Mail-Benachrichtigungen'),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='reminder_days_before',
            field=models.IntegerField(default=1, verbose_name='Erinnerung vor Termin (Tage)'),
        ),
        migrations.AddField(
            model_name='practicesettings',
            name='sms_notifications',
            field=models.BooleanField(default=False, verbose_name='SMS-Benachrichtigungen'),
        ),
    ]
