# Generated by Django 5.1.5 on 2025-08-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_practice_settings_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsettings',
            name='break_between_sessions',
            field=models.IntegerField(default=15, verbose_name='Pause zwischen Terminen (Minuten)'),
        ),
        migrations.AddField(
            model_name='calendarsettings',
            name='default_session_duration',
            field=models.IntegerField(default=30, verbose_name='Standard Behandlungsdauer (Minuten)'),
        ),
        migrations.AddField(
            model_name='calendarsettings',
            name='max_appointments_per_day',
            field=models.IntegerField(default=20, verbose_name='Maximale Termine pro Tag'),
        ),
    ]
