# Generated by Django 5.1 on 2025-08-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_calendar_settings_fields'),
    ]

    operations = [
        # Appointment Indizes
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='appointment_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient_id', 'practitioner_id'], name='appointment_patient_practitioner_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='appointment_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['series_identifier'], name='appointment_series_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='appointment_created_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['prescription_id'], name='appointment_prescription_idx'),
        ),
        
        # Prescription Indizes
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient_id', 'status'], name='prescription_patient_status_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_date'], name='prescription_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'prescription_date'], name='prescription_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient_insurance_id'], name='prescription_insurance_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['original_prescription_id'], name='prescription_original_idx'),
        ),
        
        # Patient Indizes
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patient_name_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patient_created_idx'),
        ),
        
        # BillingItem Indizes
        migrations.AddIndex(
            model_name='billingitem',
            index=models.Index(fields=['appointment_id'], name='billingitem_appointment_idx'),
        ),
        migrations.AddIndex(
            model_name='billingitem',
            index=models.Index(fields=['billing_cycle_id'], name='billingitem_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='billingitem',
            index=models.Index(fields=['created_at'], name='billingitem_created_idx'),
        ),
        
        # BillingCycle Indizes
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['insurance_provider_id', 'start_date'], name='billingcycle_provider_start_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['status', 'start_date'], name='billingcycle_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['created_at'], name='billingcycle_created_idx'),
        ),
    ]
