# Generated by Django 5.1.5 on 2025-08-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_database_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billingcycle',
            name='billingcycle_provider_start_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingcycle',
            name='billingcycle_status_start_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingcycle',
            name='billingcycle_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingitem',
            name='billingitem_appointment_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingitem',
            name='billingitem_cycle_idx',
        ),
        migrations.RemoveIndex(
            model_name='billingitem',
            name='billingitem_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescription_patient_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescription_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescription_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescription_insurance_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescription_original_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='core_appoin_appoint_5d5217_idx',
            old_name='appointment_date_status_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='core_appoin_patient_5fc7d1_idx',
            old_name='appointment_patient_practitioner_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='core_appoin_status_6824f8_idx',
            old_name='appointment_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='core_appoin_series__de38d1_idx',
            old_name='appointment_series_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='core_appoin_created_0b35cd_idx',
            old_name='appointment_created_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='core_appoin_prescri_238a5c_idx',
            old_name='appointment_prescription_idx',
        ),
    ]
